# Table creation
DROP TABLE IF EXISTS Banbury;
DROP TABLE IF EXISTS Fabric;
DROP TABLE IF EXISTS winder;
DROP TABLE IF EXISTS cutter;
DROP TABLE IF EXISTS curing;

CREATE TABLE Banbury (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DateInserted DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
sheet_width INT(3) NOT NULL
) ;

CREATE TABLE Fabric (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DateInserted DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
temperature FLOAT  NOT NULL,
sheet_width INT(3) NOT NULL
) ;

CREATE TABLE winder(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DateInserted DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
temperature FLOAT  NOT NULL
) ;

CREATE TABLE cutter (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DateInserted DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
thread_with FLOAT NOT NULL,
position_error FLOAT  NOT NULL,
speed_error FLOAT(3) NOT NULL
) ;

CREATE TABLE curing (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DateInserted DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
temperature FLOAT  NOT NULL,
molding_time_mins INT NOT NULL
) ;



