# Generated by Django 3.0.7 on 2020-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banbury_tab',
        ),
    ]
